version: "3.7"

services:
  producer:
    build:
      context: ./producer
      args:
        - RABBITMQ_HOST=${RABBITMQ_HOST}
    restart: unless-stopped
    networks:
      rabbit-network:
    depends_on:
      - rabbitmq
  consumer:
    build:
      context: ./consumer
      args:
        - RABBITMQ_HOST=${RABBITMQ_HOST}
    restart: unless-stopped
    networks:
      rabbit-network:
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    ports:
      - 5672:5672
    networks:
      rabbit-network:
        aliases:
          - ${RABBITMQ_HOST}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  rabbit-network:

volumes:
  rabbitmq-data: