version: "3.7"

services:
  smart-repo-rabbitmq:
    container_name: smart-repo-rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      rabbit-network:
        aliases:
          - ${RABBITMQ_HOST}

  elasticsearch:
    container_name: smart-repo-elastic
    image: elasticsearch:7.6.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: trial
    logging:
      driver: none
    networks:
      elk:

  kibana:
    container_name: smart-repo-kibana
    image: kibana:7.6.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana
    logging:
      driver: none
    networks:
      elk:

  smart-repo-backend:
    container_name: smart-repo-backend
    build:
      context: ../backend
      args:
        - RABBITMQ_HOST=${RABBITMQ_HOST}
        - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
    image: smart-repo-backend:latest
    ports:
      - 7777:7777
    networks:
      rabbit-network:
      elk:
    volumes:
      - ../storage:/storage
    depends_on:
      - smart-repo-rabbitmq
      - elasticsearch

  smart-repo-gui:
    container_name: smart-repo-gui
    build:
      context: ../frontend/smart-repo-gui
    image: smart-repo-gui:latest
    ports:
      - 8080:8080
    networks:
      smart-repo-network:

  smart-repo-pdf-tika:
    build:
      context: ../parsers/pdf_tika
      args:
        - RABBITMQ_HOST=${RABBITMQ_HOST}
    image: smart-repo-pdf-tika:latest
    restart: unless-stopped
    networks:
      rabbit-network:
    volumes:
      - ../storage:/storage
    depends_on:
      - smart-repo-rabbitmq

  smart-repo-txt-tika:
    build:
      context: ../parsers/txt_tika
      args:
        - RABBITMQ_HOST=${RABBITMQ_HOST}
    image: smart-repo-txt-tika:latest
    restart: unless-stopped
    networks:
      rabbit-network:
    volumes:
      - ../storage:/storage
    depends_on:
      - smart-repo-rabbitmq

networks:
  rabbit-network:
  smart-repo-network:
  elk:
    driver: bridge
