//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.31 at 09:33:34 PM CEST 
//


package https.agh_edu_pl.smart_repo.file_extension_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.agh_edu_pl.smart_repo.file_extension_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.agh_edu_pl.smart_repo.file_extension_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFileExtensionResponse }
     * 
     */
    public GetFileExtensionResponse createGetFileExtensionResponse() {
        return new GetFileExtensionResponse();
    }

    /**
     * Create an instance of {@link GetFileExtensionRequest }
     * 
     */
    public GetFileExtensionRequest createGetFileExtensionRequest() {
        return new GetFileExtensionRequest();
    }

}
