//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.16 at 02:03:04 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://agh.edu.pl/smart-repo/file-extension-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.agh_edu_pl.smart_repo.file_extension_service;
